=== app-system/app cronjob ===
apiVersion: app.sealos.io/v1
kind: App
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"app.sealos.io/v1","kind":"App","metadata":{"annotations":{},"name":"cronjob","namespace":"app-system"},"spec":{"data":{"desc":"CronJob","url":"https://<APP_DOMAIN>:443"},"displayType":"normal","i18n":{"zh":{"name":"定时任务"},"zh-Hans":{"name":"定时任务"}},"icon":"https://<APP_DOMAIN>:443/logo.svg","menuData":null,"name":"CronJob","type":"iframe"}}
    meta.helm.sh/release-name: cronjob
    meta.helm.sh/release-namespace: cronjob
  creationTimestamp: "2026-05-29T18:19:29Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cronjob
  namespace: app-system
  resourceVersion: <RESOURCE_VERSION>
  uid: <UID>
spec:
  data:
    desc: CronJob
    url: https://<APP_DOMAIN>:443
  displayType: normal
  i18n:
    zh:
      name: 定时任务
    zh-Hans:
      name: 定时任务
  icon: https://<APP_DOMAIN>:443/logo.svg
  name: CronJob
  type: iframe
=== cronjob ingress ===
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/response-header-control-remove: X-Frame-Options
    higress.io/response-header-control-update: |
      Content-Security-Policy "default-src * blob: data: *.<CLUSTER_DOMAIN> <CLUSTER_DOMAIN>; img-src * data: blob: resource: *.<CLUSTER_DOMAIN> <CLUSTER_DOMAIN>; connect-src * wss: blob: resource:; style-src 'self' 'unsafe-inline' blob: *.<CLUSTER_DOMAIN> <CLUSTER_DOMAIN> resource:; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: *.<CLUSTER_DOMAIN> <CLUSTER_DOMAIN> resource: *.baidu.com *.bdstatic.com https://js.stripe.com; frame-src 'self' *.<CLUSTER_DOMAIN> <CLUSTER_DOMAIN> mailto: tel: weixin: mtt: *.baidu.com https://js.stripe.com; frame-ancestors 'self' https://<CLUSTER_DOMAIN> https://*.<CLUSTER_DOMAIN>"
      X-Xss-Protection "1; mode=block"
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: cronjob
    meta.helm.sh/release-namespace: cronjob
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_headers "X-Frame-Options:";
      more_set_headers "Content-Security-Policy: default-src * blob: data: *.<CLUSTER_DOMAIN> <CLUSTER_DOMAIN>; img-src * data: blob: resource: *.<CLUSTER_DOMAIN> <CLUSTER_DOMAIN>; connect-src * wss: blob: resource:; style-src 'self' 'unsafe-inline' blob: *.<CLUSTER_DOMAIN> <CLUSTER_DOMAIN> resource:; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: *.<CLUSTER_DOMAIN> <CLUSTER_DOMAIN> resource: *.baidu.com *.bdstatic.com https://js.stripe.com; frame-src 'self' *.<CLUSTER_DOMAIN> <CLUSTER_DOMAIN> mailto: tel: weixin: mtt: *.baidu.com https://js.stripe.com; frame-ancestors 'self' https://<CLUSTER_DOMAIN> https://*.<CLUSTER_DOMAIN>";
      more_set_headers "X-Xss-Protection: 1; mode=block";
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, DELETE, PATCH,
      OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: https://<CLUSTER_DOMAIN>,
      https://*.<CLUSTER_DOMAIN>
    nginx.ingress.kubernetes.io/cors-max-age: "600"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  creationTimestamp: "2026-05-29T18:35:02Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cronjob
  namespace: cronjob
  resourceVersion: <RESOURCE_VERSION>
  uid: <UID>
spec:
  ingressClassName: nginx
  rules:
  - host: <APP_DOMAIN>
    http:
      paths:
      - backend:
          service:
            name: cronjob
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - <APP_DOMAIN>
    secretName: wildcard-cert
status:
  loadBalancer: {}
=== cronjob service/deploy ===
NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE   SELECTOR
service/cronjob   ClusterIP   <POD_OR_SERVICE_IP>   <none>        3000/TCP   16m   app=cronjob

NAME                      READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES                                            SELECTOR
deployment.apps/cronjob   1/1     1            1           16m   cronjob      ghcr.io/sealos-apps/cronjob/cronjob:sha-99799cd   app=cronjob

NAME                           READY   STATUS    RESTARTS   AGE   IP           NODE      NOMINATED NODE   READINESS GATES
pod/cronjob-<pod-id>   1/1     Running   0          16m   <POD_OR_SERVICE_IP>   <TEST_NODE>   <none>           <none>
