# Custom values for cronjob helm chart.
# This file only contains fields users commonly tune.

replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 10m
    memory: 128Mi

startupProbe:
  httpGet:
    path: /healthz
    port: http
  periodSeconds: 5
  failureThreshold: 24
  timeoutSeconds: 2

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 3
  timeoutSeconds: 2
  successThreshold: 2
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

cronjobConfig:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  podCpuMilliCores: 50
  podMemoryMiB: 64
