# Custom values for cronjob helm chart.
# This file only contains fields users commonly tune.

replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 10m
    memory: 128Mi

cronjobConfig:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  podCpuMilliCores: 50
  podMemoryMiB: 64
